### ISSUE TITLE
Snow Cat

### ISSUE THREAD

**Issue by EwwJavascript** [MatissesProjects/GenerateImage#172]
### Choose one

Cat

### Choose multiple

- [ ] Grass
- [ ] Blue sky
- [X] Clouds
- [ ] Rain
- [ ] Sun
- [ ] Foggy
- [X] Snow
- [ ] Sand
- [X] Hail
- [ ] Rainbow
- [X] Moon
- [X] Stars

**Comment by MatissesProjects** [comment]
this will never be seen by the worker
