### ISSUE TITLE
Play a move in marcizhu chess pls

### ISSUE THREAD

**Issue by MatthiasGN** [MatissesProjects/GenerateImage#882]
### Choose one

Car

### Choose multiple

- [ ] Grass
- [X] Blue sky
- [ ] Clouds
- [ ] Rain
- [X] Sun
- [ ] Foggy
- [ ] Snow
- [X] Sand
- [ ] Hail
- [ ] Rainbow
- [ ] Moon
- [ ] Stars
- [X] Mountains
- [ ] Ocean
- [X] Desert

**Comment by MatissesProjects** [comment]
haha hey there @MatthiasGN nice to see you around.
